title:        io
tagline:      "saglac.io"
url:          http://andhyde.com
author:
  name:       ""
  email:      ""
markdown:     redcarpet
permalink:    pretty
pygments:     true
highlighter:  rouge
paginate:     5
